apiVersion: apps/v1
kind: Deployment
metadata:
  name: monetalis-web
  namespace: monetalis
  labels:
    app: monetalis-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monetalis-web
  template:
    metadata:
      labels:
        app: monetalis-web
    spec:
      nodeSelector:
        kubernetes.io/hostname: heimdall-vm
      containers:
        - name: monetalis-web
          image: ghcr.io/blacknvcone/vates-monitalis/monetalis-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
      imagePullSecrets:
        - name: ghcr-pull-secret
