/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as CashflowRouteImport } from './routes/cashflow'
import { Route as ExportRouteImport } from './routes/export'
import { Route as ExtraPaymentsRouteImport } from './routes/extra-payments'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as InflationRouteImport } from './routes/inflation'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PaymentHistoryRouteImport } from './routes/payment-history'
import { Route as RefinanceRouteImport } from './routes/refinance'
import { Route as ScenarioCompareRouteImport } from './routes/scenario-compare'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulatorRouteImport } from './routes/simulator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CashflowRoute = CashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtraPaymentsRoute = ExtraPaymentsRouteImport.update({
  id: '/extra-payments',
  path: '/extra-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const InflationRoute = InflationRouteImport.update({
  id: '/inflation',
  path: '/inflation',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentHistoryRoute = PaymentHistoryRouteImport.update({
  id: '/payment-history',
  path: '/payment-history',
  getParentRoute: () => rootRouteImport,
} as any)
const RefinanceRoute = RefinanceRouteImport.update({
  id: '/refinance',
  path: '/refinance',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioCompareRoute = ScenarioCompareRouteImport.update({
  id: '/scenario-compare',
  path: '/scenario-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/callback': typeof CallbackRoute
  '/cashflow': typeof CashflowRoute
  '/export': typeof ExportRoute
  '/extra-payments': typeof ExtraPaymentsRoute
  '/goals': typeof GoalsRoute
  '/inflation': typeof InflationRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payment-history': typeof PaymentHistoryRoute
  '/refinance': typeof RefinanceRoute
  '/scenario-compare': typeof ScenarioCompareRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/callback': typeof CallbackRoute
  '/cashflow': typeof CashflowRoute
  '/export': typeof ExportRoute
  '/extra-payments': typeof ExtraPaymentsRoute
  '/goals': typeof GoalsRoute
  '/inflation': typeof InflationRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payment-history': typeof PaymentHistoryRoute
  '/refinance': typeof RefinanceRoute
  '/scenario-compare': typeof ScenarioCompareRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/callback': typeof CallbackRoute
  '/cashflow': typeof CashflowRoute
  '/export': typeof ExportRoute
  '/extra-payments': typeof ExtraPaymentsRoute
  '/goals': typeof GoalsRoute
  '/inflation': typeof InflationRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payment-history': typeof PaymentHistoryRoute
  '/refinance': typeof RefinanceRoute
  '/scenario-compare': typeof ScenarioCompareRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/callback'
    | '/cashflow'
    | '/export'
    | '/extra-payments'
    | '/goals'
    | '/inflation'
    | '/insights'
    | '/login'
    | '/notifications'
    | '/payment-history'
    | '/refinance'
    | '/scenario-compare'
    | '/schedule'
    | '/settings'
    | '/simulator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget'
    | '/callback'
    | '/cashflow'
    | '/export'
    | '/extra-payments'
    | '/goals'
    | '/inflation'
    | '/insights'
    | '/login'
    | '/notifications'
    | '/payment-history'
    | '/refinance'
    | '/scenario-compare'
    | '/schedule'
    | '/settings'
    | '/simulator'
  id:
    | '__root__'
    | '/'
    | '/budget'
    | '/callback'
    | '/cashflow'
    | '/export'
    | '/extra-payments'
    | '/goals'
    | '/inflation'
    | '/insights'
    | '/login'
    | '/notifications'
    | '/payment-history'
    | '/refinance'
    | '/scenario-compare'
    | '/schedule'
    | '/settings'
    | '/simulator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetRoute: typeof BudgetRoute
  CallbackRoute: typeof CallbackRoute
  CashflowRoute: typeof CashflowRoute
  ExportRoute: typeof ExportRoute
  ExtraPaymentsRoute: typeof ExtraPaymentsRoute
  GoalsRoute: typeof GoalsRoute
  InflationRoute: typeof InflationRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentHistoryRoute: typeof PaymentHistoryRoute
  RefinanceRoute: typeof RefinanceRoute
  ScenarioCompareRoute: typeof ScenarioCompareRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashflow': {
      id: '/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof CashflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extra-payments': {
      id: '/extra-payments'
      path: '/extra-payments'
      fullPath: '/extra-payments'
      preLoaderRoute: typeof ExtraPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inflation': {
      id: '/inflation'
      path: '/inflation'
      fullPath: '/inflation'
      preLoaderRoute: typeof InflationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-history': {
      id: '/payment-history'
      path: '/payment-history'
      fullPath: '/payment-history'
      preLoaderRoute: typeof PaymentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refinance': {
      id: '/refinance'
      path: '/refinance'
      fullPath: '/refinance'
      preLoaderRoute: typeof RefinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario-compare': {
      id: '/scenario-compare'
      path: '/scenario-compare'
      fullPath: '/scenario-compare'
      preLoaderRoute: typeof ScenarioCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetRoute: BudgetRoute,
  CallbackRoute: CallbackRoute,
  CashflowRoute: CashflowRoute,
  ExportRoute: ExportRoute,
  ExtraPaymentsRoute: ExtraPaymentsRoute,
  GoalsRoute: GoalsRoute,
  InflationRoute: InflationRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentHistoryRoute: PaymentHistoryRoute,
  RefinanceRoute: RefinanceRoute,
  ScenarioCompareRoute: ScenarioCompareRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
